GuiWsOpenErp
string GuiWsOpenErp::dbname
dbname
string GuiWsOpenErp::user
user
string GuiWsOpenErp::pwd
pwd
string GuiWsOpenErp::model
URL.
string GuiWsOpenErp::URL
URL.
XmlRpcValue::int32 GuiWsOpenErp::uid
uid
GuiWsOpenErp::GuiWsOpenErp(string dbname, string user, string pwd, string URL)
Constructor.
dbname Nombre de la base de datos user Nombre de usuario pwd Contrase침a de user URL URL
GuiWsOpenErp::~GuiWsOpenErp()
Destructor.
void GuiWsOpenErp::CargarVariables(string dbname, string user, string pwd, string URL)
CargarVariables Seteo de variables.
dbname user pwd URL
long int GuiWsOpenErp::Inicializar()
Inicializar se encarga de la autentificacion contra el OpenERP.
el id del usuario que se autentifica.
References NAME, VERSION.
Referenced by TemplateAFIS_webservice::comprobar, TemplateAFIS_webservice::getDatosHuella, TemplateAFIS_webservice::getDatosPersona, TemplateAFIS_webservice::getDatosPersonaOBPP, TemplateAFIS_webservice::getDatosPersonaVerificacion, TemplateAFIS_webservice::getUsuario.
XmlRpcValue GuiWsOpenErp::GetUsuario(string usuario)
GetUsuario Este metodo se encarga de buscar en la tabla res.users parametrizado con la variable "usuario".
usuario Viene de la GUI id & login.
XmlRpcValue GuiWsOpenErp::GetDatoPersona(string cedula_identidad)
GetDatoPersona Este metodo se encarga de buscar en la tabla res.partner.
cedula_identidad Viene de la GUI identification_id & name.
Referenced by TemplateAFIS_webservice::getDatosPersona.
XmlRpcValue GuiWsOpenErp::GetPersonaByOBPP(string situr_code)
GetPersonaByOBPP Este metodo se encarga de buscar todas las personas a la cual pertene una obpp, para ello se parametriza la busquedad con el cdigo situr.
situr_code Viene de la GUI Valores de la OBPP
References NAME, VERSION.
Referenced by TemplateAFIS_webservice::getDatosPersonaOBPP.
XmlRpcValue GuiWsOpenErp::GetDatoidImagen(long int partner_id, string hand, string finger)
GetDatoidImagen Este metodo se encarga de obtener el id de un registro en la tabla res.partner.fingerprint para ello la busquedad es parametrizada con partner_id, hand y finger.
partner_id Viene de la GUI hand Viene de la GUI finger Viene de la GUI result_read es un struct XmlRpcValue
XmlRpcValue GuiWsOpenErp::getDatoPersonaVerificacion(string cedula)
getDatoPersonaVerificacion Este metodo se encarga de buscar los datos de la persona, a la cual se le verifica la huella.
cedula Viene de la GUI Datos de verificaci칩n para una persona
Referenced by TemplateAFIS_webservice::getDatosPersonaVerificacion.
XmlRpcValue GuiWsOpenErp::buscarProyecto(int id_obpp)
XmlRpcValue GuiWsOpenErp::getDatoHuella(string cedula, string &mano, int &dedo)
getDatoHuella Este metodo se encarga de buscar las huellas que tiene registrado un integrante de la obpp, cuando se va a verificar.
cedula mano dedo Retorna mano y dedo por referencia. Y datos de la Huella por XmlRpcValue
Referenced by TemplateAFIS_webservice::getDatosHuella.