Fingerprint
string Fingerprint::dbname
dbname
Referenced by TemplateAFIS_webservice::guardarIncidencia.
string Fingerprint::user
user
string Fingerprint::pwd
pwd
string Fingerprint::URL
URL.
Referenced by TemplateAFIS_webservice::borrarHuella, TemplateAFIS_webservice::comprobar, TemplateAFIS_webservice::getDatosIdImagen, TemplateAFIS_webservice::guardarIncidencia, TemplateAFIS_webservice::OnEnroll, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify, TemplateAFIS_webservice::salvarJPEG.
Fingerprint::Fingerprint(string dbname, string user, string pwd, string URL)
Constructor de la clase Fingerprint.
long int Fingerprint::getUID()
Get UID: Realiza login. Se crea la matriz (array) con cada parámetro que Odoo necesita para loguear al usuario (chequea la base de datos, usuario y clave para el logueo). Todos los valores son procesados por XmlRpcValue.
Retorna UID de Usuario URE.Si es 0 devuelve error (credenciales erradas). Sólo los usuarios con permisos de URE (Coordinadores de las Unidades Receptoras Estadales) pueden usar el sistema de huellas.
bool Fingerprint::isURE(XmlRpcClient server_search)
Is URE: Pregunta si un usuario es URE. Se buscan la huella y la plantilla a partir de una cédula u otro identificador del vocero.
server_search Servidor XML_RPC model es el modelo (tablas de la base de datos) de Odoo. Retorna si es URE o no es URE. Esta función devuelve los IDs de las huellas que tenga la persona.
Referenced by TemplateAFIS_webservice::comprobar.
XmlRpcValue Fingerprint::searchPersona(XmlRpcClient server_search, string cedula="", long int partner_id=0)
Search Persona: Busca una persona por cédula o partner_id. OPTIMIZAR: Cambiar todos los search posibles por browse.
server_search Servidor XML_RPC cedula Cédula persona partner_id Id Partner Retorna XmlRpcValue resultante
Referenced by TemplateAFIS_webservice::borrarHuella, TemplateAFIS_webservice::getDatosIdImagen, TemplateAFIS_webservice::OnEnroll, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify, TemplateAFIS_webservice::salvarJPEG.
XmlRpcValue Fingerprint::readVatPersona(XmlRpcClient server_search, XmlRpcValue partner_id)
Read Vat Persona: Ubica las huellas de la persona en base a su por partner_id.
server_search Servidor XML_RPC partner_id Id Partner Retorna XmlRpcValue resultante
Referenced by TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify.
XmlRpcValue Fingerprint::searchFingerprint(XmlRpcClient server_search, int finger=0, string hand="", long int partner_id=0)
Search Fingerprint: Busca una huella específica por dedo, mano e Id partner.
partner_id: identifica el registro de la persona en la base de datos de Odoo. finger: es el dedo (0 a 4, pulgar, índice, medio, anular y meñique). hand: es la mano o pie (MD, MI, PD, PI). server_search Servidor XML_RPC finger Dedo hand Mano partner_id Id Partner Retorna XmlRpcValue resultante
Referenced by TemplateAFIS_webservice::OnEnroll.
XmlRpcValue Fingerprint::readFingerprintImageId(XmlRpcClient server_search, XmlRpcValue fingerprint_id)
Método readFingerprintImageId: Obtiene el campo image_id de la tabla.
Sirve para ubicar la imagen que se muestra para cada huella. De la imagen podemos obtener la plantilla (template que tiene la información geométrica de las minucias.), pero en realidad se guarda para mostrarla. Se hacen las comparaciones en base a las plantillas que genera automáticamente el captahuellas.El captahuellas escanea la huella y mejora brillo y contraste automáticamente. Almacena un mapa de bits. El mismo captahuellas procesa la imagen y extrae las minucias según los conceptos de la imagen (islas, bifurcaciones, deltas, vacíos, etc.) Esas minucias se guardan en un archivo binario de unos 200 - 300 bytes. Y el mapa de bits también se almacena. Con ese último método, se busca la imagen de la huella. La comparación en base a las planillas es usada para saber si una huella pertenece a una persona (verificación) o a qué persona pertenece una huella (identificación), se comparan plantillas, no imágenes. Es para mostrarla en el cliente.res.partner.fingerprint fingerprint_id, que es el id de la tabla: res.partner.fingerprint. server_search Servidor XML_RPC fingerprint_id Id tabla res_partner_fingerprint Retorna XmlRpcValue resultante
XmlRpcValue Fingerprint::readFingerprint(XmlRpcClient server_search, int finger=0, string hand="", long int partner_id=0)
Método readFingerprint: Es una función polimorfa.
Es una función de búsqueda general. Dependiendo del input, hace diferentes búsquedas. Recibe los parámetros int finger = 0, string hand = "", long int partner_id = 0. Obtiene todos los campos de la tabla: res.partner.fingerprint.OPTIMIZAR: No es seguro que se use actualmente. Es posible que se elimine en la revisión. server_search Servidor XML_RPC finger Dedo hand Mano partner_id Id Partner Retorna XmlRpcValue resultante
Referenced by TemplateAFIS_webservice::getDatosIdImagen, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify.
XmlRpcValue Fingerprint::readFingerprint(XmlRpcClient server_search, XmlRpcValue fingerprint_id)
Método readFingerprint: Es una función polimorfa. Recibe los parámetros XmlRpcClient server_search, XmlRpcValue fingerprint_id.
Obtiene todos los campos de la tabla: res.partner.fingerprint. server_search Servidor XML_RPC fingerprint_id Id Fingerprint Retorna XmlRpcValue resultante
XmlRpcValue Fingerprint::readFingerprintImage(XmlRpcClient server_search, int finger=0, string hand="", long int partner_id=0)
Método readFingerprintImage: Obtiene todos los campos de la tabla res.partner.fingerprint.image.
Es una función de consulta general, pero en base a dedo, mano y el ID de la persona.OPTIMIZAR: No se esta usando server_search Servidor XML_RPC finger Finger hand Mano partner_id Id Partner Retorna XmlRpcValue resultante
Referenced by TemplateAFIS_webservice::salvarJPEG.
XmlRpcValue Fingerprint::searchFingerprintImage(XmlRpcClient server_search, long int fingerprint_id=0)
Método searchFingerprintImage: Obtiene el ID de la tabla: res.partner.fingerprint.image.
OPTIMIZAR: No se usa porque ya lo resuelve Odoo server_search Servidor XML_RPC fingerprint_id Id Fingerprint Retorna XmlRpcValue resultante
int Fingerprint::insertarFingerprintImg(unsigned char *buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char *image, long int image_size)
Método insertarFingerprintImg: Inserta los campos en las tablas: res.partner.fingerprint.image y res.partner.fingerprint.
OPTIMIZAR: No se usa en esta versión. Actualmente usa el modelo webservice.methodsSe sustituyó por el método: int insertarFingerprintWebService(unsigned char * &buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char * &image, long int image_size) buffer_template Huella hash Hash finger Dedo hand Mano partner_id Id Partner template_size Tamaño Huella image_height Alto imagen image_width Ancho imagen image Imagen image_size Tamaño imagen Retorna Estado de inserción
char* Fingerprint::base64(unsigned char *&input, long int length)
Método base64: Convierte de unsigned char * a Base64.
Sirve para convertir texto en UUCODE de base 64, que se usa para «desbinarizar» la plantilla binaria. Se desbinariza por compatibilidad con los tipos de datos de XML RPC. Las imágenes binarias en internet se movían como texto UUEncoded. XML RPC sólo acepta datos en matrices no-binarias. Si el argumento de la petición es un template, debemos codificarla a texto. Odoo admite peticiones a su webservice en XML. input Raw length Tamaño Raw Texto en base64
unsigned char* Fingerprint::base64_decodestring(std::string text)
Método base64_decodestring: Decodifica un string Base64 a un unsigned char *.
text Texto Base64 Raw
char* Fingerprint::str2md5(const char *str, int length)
Método str2md5: Codifica un string a MD5.
Sirve para convertir una cadena en MD5. Se usa para hashear la fecha, la hora y otras cosas, como una forma de crear una cookie para certificar cada conexión de un cliente con el servidor. Si la fecha y la hora del cliente están muy lejos de la del servidor, la conexión falla. str Texto length Tamaño texto Texto en MD5
int Fingerprint::insertarFingerprintWebService(unsigned char *&buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char *&image, long int image_size)
Método insertarFingerprintWebService: Inserta los campos en las tablas: res.partner.fingerprint.image y res.partner.fingerprint.
Es una función para insertar las huellas a Odoo. Toma los datos del cliente, los arma en una matriz (array) que XML RPC pueda interpretar, e invoca el método correspondiente en el webservice de Odoo. Convierte la imagen de binario a texto y de texto a cadena XML RPC. webservice.methods es el modelo de Odoo que instancia el webservice de Odoo. Odoo tiene su propio cliente web, y se relaciona con la base de datos mediante ese webservice «interno». buffer_template Huella hash Hash finger Dedo hand Mano partner_id Id Partner template_size Tamaño Huella image_height Alto imagen image_width Ancho imagen image Imagen image_size Tamaño imagen Retorna Estado de inserción
Referenced by TemplateAFIS_webservice::OnEnroll.
bool Fingerprint::actualizarFingerprintImg(unsigned char *buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char *image, long int image_size)
Método actualizarFingerprintImg: Actualiza un registro en la tabla res.partner.fingerprint.image. Es la función para actualizar huellas. Para actualizar primero se ubica (searchFingerprint) y con ese ID se sobreescribe.
OPTIMIZAR: * No está activa en esta versión Se sustituyó por la bool actualizarFingerprintImg(unsigned char *buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char * image, long int image_size) buffer_template Huella hash Hash finger Dedo hand Mano partner_id Id Partner template_size Tamaño Huella image_height Alto imagen image_width Ancho imagen image Imagen image_size Tamaño imagen Retorna Estado de actualización
bool Fingerprint::actualizarFingerprintWebService(unsigned char *&buffer_template, string hash, int finger, string hand, long int partner_id, int template_size, int image_height, int image_width, unsigned char *&image, long int image_size)
Método actualizarFingerprintWebService: Actualiza un registro en la tabla: res.partner.fingerprint.
Función actual para actualizar huellas usa el browse / read / search buffer_template Huella hash Hash finger Dedo hand Mano partner_id Id Partner template_size Tamaño Huella image_height Alto imagen image_width Ancho imagen image Imagen image_size Tamaño imagen Retorna Estado de actualización
Referenced by TemplateAFIS_webservice::OnEnroll.
int Fingerprint::borrarFingerprintImg(int finger, string hand, long int partner_id)
Método borrarFingerprintImg: Borrar un registro de la tabla: res.partner.fingerprint.image. Función para eliminar huellas.
OPTIMIZAR: Puede que no se use porque usa usa res.partner.fingerprint.image en lugar de webservice.methods. finger Dedo hand Mano partner_id Id Partner Retorna Estado de borrado
Referenced by TemplateAFIS_webservice::borrarHuella.