SHA512
typedef unsigned char SHA512::uint8
typedef unsigned long SHA512::uint32
typedef unsigned long long SHA512::uint64
const unsigned long long SHA512::sha512_k[]
Referenced by transform.
const unsigned int SHA512::SHA384_512_BLOCK_SIZE
Referenced by final, update.
const unsigned int SHA512::DIGEST_SIZE
Referenced by sha512.
unsigned int SHA512::m_tot_len
Referenced by final, init, update.
unsigned int SHA512::m_len
Referenced by final, init, update.
unsigned char SHA512::m_block[2 *SHA384_512_BLOCK_SIZE][2 *SHA384_512_BLOCK_SIZE]
Referenced by final, update.
uint64 SHA512::m_h[8][8]
Referenced by final, init, transform.
void SHA512::init()
References m_h, m_len, m_tot_len.
Referenced by sha512.
void SHA512::update(const unsigned char *message, unsigned int len)
References m_block, m_len, m_tot_len, SHA384_512_BLOCK_SIZE, transform.
Referenced by sha512.
void SHA512::final(unsigned char *digest)
References m_block, m_h, m_len, m_tot_len, SHA2_UNPACK32, SHA2_UNPACK64, SHA384_512_BLOCK_SIZE, transform.
Referenced by sha512.
void SHA512::transform(const unsigned char *message, unsigned int block_nb)
References m_h, SHA2_CH, SHA2_MAJ, SHA2_PACK64, SHA512_F1, SHA512_F2, SHA512_F3, SHA512_F4, sha512_k.
Referenced by final, update.