UFMatcher.h
UFM_API
UFM_STATUS
Referenced by TemplateAFIS_webservice::initMatcher, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify, TemplateAFIS_webservice::unInitMatcher.
UFM_OK
Referenced by TemplateAFIS_webservice::initMatcher, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify, TemplateAFIS_webservice::unInitMatcher.
UFM_ERROR
UFM_ERR_NO_LICENSE
UFM_ERR_LICENSE_NOT_MATCH
UFM_ERR_LICENSE_EXPIRED
UFM_ERR_NOT_SUPPORTED
UFM_ERR_INVALID_PARAMETERS
UFM_ERR_MATCH_TIMEOUT
UFM_ERR_MATCH_ABORTED
UFM_ERR_TEMPLATE_TYPE
UFM_PARAM_FAST_MODE
Referenced by TemplateAFIS_webservice::GetFastMode.
UFM_PARAM_SECURITY_LEVEL
Referenced by TemplateAFIS_webservice::GetSecurityLevel.
UFM_PARAM_USE_SIF
UFM_TEMPLATE_TYPE_SUPREMA
UFM_TEMPLATE_TYPE_ISO19794_2
UFM_TEMPLATE_TYPE_ANSI378
typedef void* HUFMatcher
UFM_STATUS UFM_API UFM_Create(HUFMatcher *phMatcher)
Referenced by TemplateAFIS_webservice::initMatcher.
UFM_STATUS UFM_API UFM_Delete(HUFMatcher hMatcher)
Referenced by TemplateAFIS_webservice::unInitMatcher.
UFM_STATUS UFM_API UFM_GetParameter(HUFMatcher hMatcher, int nParam, void *pValue)
Referenced by TemplateAFIS_webservice::GetFastMode, TemplateAFIS_webservice::GetSecurityLevel.
UFM_STATUS UFM_API UFM_SetParameter(HUFMatcher hMatcher, int nParam, void *pValue)
UFM_STATUS UFM_API UFM_Verify(HUFMatcher hMatcher, unsigned char *pTemplate1, int nTemplate1Size, unsigned char *pTemplate2, int nTemplate2Size, int *bVerifySucceed)
Referenced by TemplateAFIS_webservice::OnVerify.
UFM_STATUS UFM_API UFM_Identify(HUFMatcher hMatcher, unsigned char *pTemplate1, int nTemplate1Size, unsigned char **ppTemplate2, int *pnTemplate2Size, int nTemplate2Num, int nTimeout, int *pnMatchTemplate2Index)
Referenced by TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify.
UFM_STATUS UFM_API UFM_AbortIdentify(HUFMatcher hMatcher)
UFM_STATUS UFM_API UFM_IdentifyInit(HUFMatcher hMatcher, unsigned char *pTemplate1, int nTemplate1Size)
UFM_STATUS UFM_API UFM_IdentifyNext(HUFMatcher hMatcher, unsigned char *pTemplate2, int nTemplate2Size, int *bIdentifySucceed)
UFM_STATUS UFM_API UFM_RotateTemplate(HUFMatcher hMatcher, unsigned char *pTemplate, int nTemplateSize)
UFM_STATUS UFM_API UFM_GetErrorString(UFM_STATUS res, char *szErrorString)
Referenced by TemplateAFIS_webservice::initMatcher, TemplateAFIS_webservice::OnIdentify, TemplateAFIS_webservice::OnIdentifyOnVerify, TemplateAFIS_webservice::OnVerify.
UFM_STATUS UFM_API UFM_SetTemplateType(HUFMatcher hMatcher, int nTemplateType)
Referenced by TemplateAFIS_webservice::OnSetTemplateType.
UFM_STATUS UFM_API UFM_GetTemplateType(HUFMatcher hMatcher, int *nTemplateType)